In [1]:
import pandas as pd
from scripts.load import *

Adding product_list.xlsx ...
Adding user_credit_card.pickle ...
Adding user_data.json ...
Adding user_job.csv ...
Adding merchant_data.html ...
Adding order_with_merchant_data1.parquet ...
Adding order_with_merchant_data2.parquet ...
Adding order_with_merchant_data3.csv ...
Adding staff_data.html ...
Adding campaign_data.csv ...
Adding transactional_campaign_data.csv ...
Adding line_item_data_prices1.csv ...
Adding line_item_data_prices2.csv ...
Adding line_item_data_prices3.parquet ...
Adding line_item_data_products1.csv ...
Adding line_item_data_products2.csv ...
Adding line_item_data_products3.parquet ...
Adding order_data_20200101-20200701.parquet ...
Adding order_data_20200701-20211001.pickle ...
Adding order_data_20211001-20220101.csv ...
Adding order_data_20220101-20221201.xlsx ...
Adding order_data_20221201-20230601.json ...
Adding order_data_20230601-20240101.html ...
Adding order_delays.html ...



--------------------------------------------------
Read Complete
Access the DataFrame of each file using the `all` dictionary
e.g. all["filename"]

below are the available keys for access:
1:	product_list.xlsx
2:	user_credit_card.pickle
3:	user_data.json
4:	user_job.csv
5:	merchant_data.html
6:	order_with_merchant_data1.parquet
7:	order_with_merchant_data2.parquet
8:	order_with_merchant_data3.csv
9:	staff_data.html
10:	campaign_data.csv
11:	transactional_campaign_data.csv
12:	line_item_data_prices1.csv
13:	line_item_data_prices2.csv
14:	line_item_data_prices3.parquet
15:	line_item_data_products1.csv
16:	line_item_data_products2.csv
17:	line_item_data_products3.parquet
18:	order_data_20200101-20200701.parquet
19:	order_data_20200701-20211001.pickle
20:	order_data_20211001-20220101.csv
21:	order_data_20220101-20221201.xlsx
22:	order_data_20221201-20230601.json
23:	order_data_20230601-20240101.html
24:	order_delays.html

In [12]:
df_merchant_data = all['merchant_data.html'][0]

(5000, 9)

In [15]:
print(df_merchant_data.shape)
print(df_merchant_data.nunique())
print(df_merchant_data.isna().sum())

(5000, 9)
Unnamed: 0        5000
merchant_id       4812
creation_date     5000
name               529
street            5000
state               50
city                98
country            249
contact_number    5000
dtype: int64
Unnamed: 0        0
merchant_id       0
creation_date     0
name              0
street            0
state             0
city              0
country           0
contact_number    0
dtype: int64

In [42]:
df_merchant_data.sample(20)

,Unnamed: 0,merchant_id,creation_date,name,street,state,city,country,contact_number
734,734,MERCHANT31246,2020-06-17 05:32:29,iRecycle,301 East Plain mouth,Arkansas,Glendale,Iraq,1-770-077-8960
611,611,MERCHANT9292,2022-07-24 17:31:59,Impact Forecasting (Aon),6255 Points shire,Nevada,Jersey,Ecuador,(629)878-8696
4738,4738,MERCHANT39811,2020-01-30 04:37:30,Equal Pay for Women,90274 Summit stad,New Jersey,Chandler,Sierra Leone,597-628-8900
471,471,MERCHANT17896,2021-12-24 20:49:10,Quid,4655 North Courts fort,Iowa,Glendale,Cayman Islands,(330)434-9482
3888,3888,MERCHANT38719,2023-11-06 07:44:25,Splunk,2325 South Lodge mouth,Illinois,Baltimore,Zimbabwe,1-414-310-0200
2851,2851,MERCHANT21383,2020-03-21 15:47:06,AtSite,40018 Lake Burg ton,West Virginia,Denver,Kazakhstan,496-439-9902
1591,1591,MERCHANT18780,2023-10-15 05:45:54,Bing,39279 Shoal mouth,Texas,Los Angeles,Chile,115-086-6560
3278,3278,MERCHANT25824,2023-06-28 06:03:04,Azavea,617 Mountain side,Arizona,San Francisco,Morocco,(562)346-0813
412,412,MERCHANT59376,2020-10-19 14:45:50,Bloomberg,9341 Run fort,New York,Glendale,Norfolk Island,1-649-813-8081
1487,1487,MERCHANT64089,2021-04-28 17:24:05,SnapSense,86344 East Cliff burgh,Illinois,Miami,Samoa,913.137.2647
1676,1676,MERCHANT20374,2023-02-07 16:13:30,"Lumesis, Inc.",7099 Shoals mouth,Nevada,Norfolk,Jamaica,(686)677-5415
4875,4875,MERCHANT60631,2020-10-25 23:39:14,Code for America,5294 North Walk borough,Florida,North Las Vegas,Dominican Republic,1-952-507-5492
4148,4148,MERCHANT17025,2022-03-17 23:51:44,Abt Associates,4481 Locks berg,Utah,Glendale,Mauritania,899-592-1249
4264,4264,MERCHANT58689,2023-09-18 13:52:13,Mozio,94552 Turnpike land,Iowa,Lexington-Fayette,Greece,232-687-0315
1786,1786,MERCHANT53917,2023-11-06 18:48:47,ASC Partners,8254 South Land land,Idaho,San Francisco,Lesotho,728-563-8235
2397,2397,MERCHANT31240,2020-01-01 18:33:15,"Lumesis, Inc.",991 Wall town,Alabama,Arlington,Comoros,728.682.3471
2273,2273,MERCHANT11648,2020-11-03 04:50:53,CrowdANALYTIX,492 Lane haven,Oklahoma,Indianapolis,Lao People's Democratic Republic,1-748-579-9242
1983,1983,MERCHANT59860,2022-12-18 16:05:57,NERA Economic Consulting,1718 Station side,North Carolina,San Francisco,Syrian Arab Republic,373.636.4304
2414,2414,MERCHANT41177,2021-08-26 15:05:08,T. Rowe Price,2669 New Mountains fort,Arkansas,El Paso,United States Minor Outlying Islands,178.454.6122
4248,4248,MERCHANT17176,2021-11-19 01:22:34,karmadata,8949 Lake Bridge side,North Carolina,Lexington-Fayette,Afghanistan,396-051-4031

In [47]:
print(df_merchant_data[df_merchant_data['name'] == 'Whitby Group'])

      Unnamed: 0    merchant_id        creation_date          name  \
0              0  MERCHANT53971  2022-06-28 11:42:04  Whitby Group
587          587  MERCHANT42785  2020-07-09 05:01:04  Whitby Group
805          805  MERCHANT14578  2022-06-27 02:21:19  Whitby Group
954          954  MERCHANT33507  2023-11-17 21:23:22  Whitby Group
1298        1298  MERCHANT18274  2020-01-10 00:27:55  Whitby Group
1363        1363  MERCHANT29283  2022-12-03 17:43:48  Whitby Group
3737        3737  MERCHANT44482  2020-12-09 14:23:47  Whitby Group
4424        4424  MERCHANT18217  2023-05-30 16:15:08  Whitby Group

                      street           state            city  \
0        813 North Isle bury  South Carolina           Boise
587      724 Circles borough        Virginia    Philadelphia
805        1197 Mall chester        Kentucky        Glendale
954    79822 East Track port    South Dakota         Norfolk
1298   152 South Plains land        Oklahoma  Virginia Beach
1363      21317 Islands town    Pennsylvania   San Francisco
3737        17064 Track port        Maryland          Tucson
4424  308 New Junctions port            Ohio         Wichita

                          country  contact_number
0               Brunei Darussalam    661.157.5528
587                         Chile   (140)809-6007
805                 Guinea-Bissau    955-944-0301
954                        Malawi    804.906.1416
1298                      Lebanon   (751)982-5865
1363  Falkland Islands (Malvinas)  1-128-124-7858
3737                     Bulgaria    478-076-2167
4424        Virgin Islands (U.S.)  1-282-802-3558